//
//  StyleKitName.js
//  ProjectName
//
//  Created by Mike on 10/2/20.
//  Copyright © 2020 PixelCut. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



//// APIs you can use in your code:
//
// Available methods for drawing into <canvas> elements:
//    StyleKitName.drawLogosPage1Canvas(canvas, targetFrame*, resizing*)
//
// NOTE: 'canvas' parameter can be either a <canvas> element object, or the id of a <canvas> element in your document.
//
// NOTE: Parameters marked with the '*' symbol are optional
//
// NOTE: Possible arguments for 'resizing' parameter in drawing methods are:
//   'aspectfit': The content is proportionally resized to fit into the target rectangle.
//   'aspectfill': The content is proportionally resized to completely fill the target rectangle.
//   'stretch': The content is stretched to match the entire target rectangle.
//   'center': The content is centered in the target rectangle, but it is NOT resized.
//
// Available Utilities:
//    StyleKitName.clearCanvas(canvas)
//    StyleKitName.makeRect(x, y, width, height)


//// Create StyleKit Object
var StyleKitName = {};
(function() {

    //// Drawing Methods

    function drawLogosPage1Canvas(canvas, targetFrame, resizing) {
        //// General Declarations
        canvas = initializeCanvas(typeof canvas === 'string' ? document.getElementById(canvas) : canvas);
        var context = canvas.getContext('2d');
        var pixelRatio = canvas.paintCodePixelRatio;
        
        //// Resize to Target Frame
        context.save();
        var resizedFrame = applyResizingBehavior(resizing, makeRect(0, 0, 1075, 385), targetFrame);
        context.translate(resizedFrame.x, resizedFrame.y);
        context.scale(resizedFrame.w / 1075, resizedFrame.h / 385);


        //// Color Declarations
        var fillColor2 = 'rgba(255, 255, 254, 1)';
        var fillColor3 = 'rgba(40, 106, 166, 1)';
        var fillColor4 = 'rgba(220, 62, 56, 1)';
        var gradientColor = 'rgba(218, 182, 97, 1)';
        var gradientColor2 = 'rgba(236, 228, 141, 1)';
        var gradientColor3 = 'rgba(139, 89, 47, 1)';
        var gradientColor4 = 'rgba(219, 183, 99, 1)';
        var gradientColor5 = 'rgba(128, 75, 44, 1)';
        var gradientColor6 = 'rgba(38, 34, 29, 1)';
        var gradientColor7 = 'rgba(159, 131, 73, 1)';
        var fillColor5 = 'rgba(98, 76, 47, 1)';

        //// Gradient Declarations
        function gradient(g) {
            g.addColorStop(0, gradientColor);
            g.addColorStop(0.05, gradientColor);
            g.addColorStop(0.48, gradientColor2);
            g.addColorStop(0.84, gradientColor3);
            g.addColorStop(0.92, gradientColor4);
            g.addColorStop(0.98, gradientColor5);
            g.addColorStop(1, gradientColor6);
            return g;
        }
        function gradient2(g) {
            g.addColorStop(0, gradientColor7);
            g.addColorStop(0, gradientColor7);
            g.addColorStop(0.68, gradientColor3);
            g.addColorStop(0.92, gradientColor4);
            g.addColorStop(0.98, gradientColor5);
            g.addColorStop(1, gradientColor6);
            return g;
        }

        //// Group 22
        //// Bezier Drawing
        context.beginPath();
        context.moveTo(237.23, 86.29);
        context.lineTo(297.95, 0.44);
        context.lineTo(255.29, 0.39);
        context.lineTo(201.58, 74.16);
        context.bezierCurveTo(214.09, 76.75, 226.04, 80.86, 237.23, 86.29);
        context.closePath();
        context.fillStyle = fillColor2;
        context.fill();


        //// Bezier 2 Drawing
        context.beginPath();
        context.moveTo(268.39, 106.42);
        context.lineTo(338.98, 0.38);
        context.lineTo(297.95, 0.44);
        context.lineTo(237.23, 86.29);
        context.bezierCurveTo(248.45, 91.74, 258.9, 98.52, 268.39, 106.42);
        context.closePath();
        context.fillStyle = fillColor3;
        context.fill();


        //// Bezier 3 Drawing
        context.beginPath();
        context.moveTo(255.29, 0.39);
        context.lineTo(213.98, 0.4);
        context.lineTo(176.71, 49.64);
        context.lineTo(187.35, 71.94);
        context.bezierCurveTo(192.16, 72.47, 196.91, 73.2, 201.58, 74.16);
        context.lineTo(255.29, 0.39);
        context.closePath();
        context.fillStyle = fillColor4;
        context.fill();


        //// Bezier 4 Drawing
        context.beginPath();
        context.moveTo(170.44, 57.91);
        context.lineTo(170.41, 57.95);
        context.lineTo(175.21, 64.27);
        context.lineTo(170.44, 57.91);
        context.closePath();
        context.fillStyle = fillColor4;
        context.fill();


        //// Bezier 5 Drawing
        context.beginPath();
        context.moveTo(139.3, 74.16);
        context.lineTo(85.65, 0.41);
        context.lineTo(42.87, 0.44);
        context.lineTo(103.63, 86.3);
        context.bezierCurveTo(114.83, 80.86, 126.78, 76.74, 139.3, 74.16);
        context.closePath();
        context.fillStyle = fillColor2;
        context.fill();


        //// Bezier 6 Drawing
        context.beginPath();
        context.moveTo(42.87, 0.44);
        context.lineTo(-0.21, 0.33);
        context.lineTo(74.49, 104.8);
        context.bezierCurveTo(83.44, 97.59, 93.19, 91.36, 103.63, 86.3);
        context.lineTo(42.87, 0.44);
        context.closePath();
        context.fillStyle = fillColor4;
        context.fill();


        //// Bezier 7 Drawing
        context.beginPath();
        context.moveTo(170.43, 70.99);
        context.bezierCurveTo(173.83, 70.99, 177.19, 71.14, 180.53, 71.35);
        context.lineTo(175.21, 64.27);
        context.lineTo(170.41, 57.95);
        context.lineTo(126.42, 0.44);
        context.lineTo(85.65, 0.41);
        context.lineTo(139.3, 74.16);
        context.bezierCurveTo(149.35, 72.08, 159.77, 70.99, 170.43, 70.99);
        context.closePath();
        context.fillStyle = fillColor3;
        context.fill();


        //// Group
        context.save();

        //// Clip Clip

        oval(context, 31.65, 85.33, 277.6, 277.6);
        context.clip();



        //// Oval Drawing
        oval(context, 31.65, 85.33, 277.6, 277.6);
        context.fillStyle = gradient(context.createLinearGradient(314.54, 194.86, 9.5, 256.86));
        context.fill();


        context.restore();



        //// Group 2
        context.save();

        //// Clip Clip 2

        oval(context, 36.15, 89.83, 268.6, 268.6);
        context.clip();



        //// Oval 3 Drawing
        oval(context, 36.15, 89.83, 268.6, 268.6);
        context.fillStyle = gradient(context.createLinearGradient(41.65, 276.72, 362.53, 145.73));
        context.fill();


        context.restore();



        //// Group 3
        context.save();

        //// Clip Clip 3

        context.beginPath();
        context.moveTo(156.67, 176.87);
        context.lineTo(138.93, 176.98);
        context.bezierCurveTo(133.61, 177.01, 130.33, 179.69, 128.64, 185.05);
        context.lineTo(128.64, 185.05);
        context.lineTo(125.91, 193.68);
        context.bezierCurveTo(125.64, 194.56, 125.46, 195.36, 125.36, 196.09);
        context.lineTo(125.36, 196.09);
        context.bezierCurveTo(124.86, 199.84, 126.72, 201.68, 131.18, 201.66);
        context.lineTo(131.18, 201.66);
        context.lineTo(148.92, 201.55);
        context.bezierCurveTo(154.25, 201.51, 157.53, 198.84, 159.22, 193.48);
        context.lineTo(159.22, 193.48);
        context.lineTo(161.94, 184.84);
        context.bezierCurveTo(162.21, 183.97, 162.39, 183.17, 162.49, 182.44);
        context.lineTo(162.49, 182.44);
        context.bezierCurveTo(162.98, 178.72, 161.16, 176.87, 156.77, 176.87);
        context.lineTo(156.77, 176.87);
        context.bezierCurveTo(156.74, 176.87, 156.7, 176.87, 156.67, 176.87);
        context.closePath();
        context.moveTo(131.63, 194.59);
        context.bezierCurveTo(131.69, 194.2, 131.83, 193.69, 132.03, 193.06);
        context.lineTo(132.03, 193.06);
        context.lineTo(134.37, 185.59);
        context.bezierCurveTo(135.09, 183.33, 136.39, 182.23, 138.57, 182.22);
        context.lineTo(138.57, 182.22);
        context.lineTo(153.76, 182.13);
        context.bezierCurveTo(155.52, 182.12, 156.44, 182.26, 156.21, 183.97);
        context.lineTo(156.21, 183.97);
        context.bezierCurveTo(156.16, 184.37, 156.05, 184.88, 155.86, 185.46);
        context.lineTo(155.86, 185.46);
        context.lineTo(153.52, 192.93);
        context.bezierCurveTo(152.81, 195.12, 151.5, 196.26, 149.33, 196.27);
        context.lineTo(149.33, 196.27);
        context.lineTo(134.13, 196.36);
        context.bezierCurveTo(134.05, 196.36, 133.97, 196.36, 133.89, 196.36);
        context.lineTo(133.89, 196.36);
        context.bezierCurveTo(132.28, 196.36, 131.42, 196.23, 131.63, 194.59);
        context.closePath();
        context.clip();



        //// Bezier 8 Drawing
        context.beginPath();
        context.moveTo(156.67, 176.87);
        context.lineTo(138.93, 176.98);
        context.bezierCurveTo(133.61, 177.01, 130.33, 179.69, 128.64, 185.05);
        context.lineTo(128.64, 185.05);
        context.lineTo(125.91, 193.68);
        context.bezierCurveTo(125.64, 194.56, 125.46, 195.36, 125.36, 196.09);
        context.lineTo(125.36, 196.09);
        context.bezierCurveTo(124.86, 199.84, 126.72, 201.68, 131.18, 201.66);
        context.lineTo(131.18, 201.66);
        context.lineTo(148.92, 201.55);
        context.bezierCurveTo(154.25, 201.51, 157.53, 198.84, 159.22, 193.48);
        context.lineTo(159.22, 193.48);
        context.lineTo(161.94, 184.84);
        context.bezierCurveTo(162.21, 183.97, 162.39, 183.17, 162.49, 182.44);
        context.lineTo(162.49, 182.44);
        context.bezierCurveTo(162.98, 178.72, 161.16, 176.87, 156.77, 176.87);
        context.lineTo(156.77, 176.87);
        context.bezierCurveTo(156.74, 176.87, 156.7, 176.87, 156.67, 176.87);
        context.closePath();
        context.moveTo(131.63, 194.59);
        context.bezierCurveTo(131.69, 194.2, 131.83, 193.69, 132.03, 193.06);
        context.lineTo(132.03, 193.06);
        context.lineTo(134.37, 185.59);
        context.bezierCurveTo(135.09, 183.33, 136.39, 182.23, 138.57, 182.22);
        context.lineTo(138.57, 182.22);
        context.lineTo(153.76, 182.13);
        context.bezierCurveTo(155.52, 182.12, 156.44, 182.26, 156.21, 183.97);
        context.lineTo(156.21, 183.97);
        context.bezierCurveTo(156.16, 184.37, 156.05, 184.88, 155.86, 185.46);
        context.lineTo(155.86, 185.46);
        context.lineTo(153.52, 192.93);
        context.bezierCurveTo(152.81, 195.12, 151.5, 196.26, 149.33, 196.27);
        context.lineTo(149.33, 196.27);
        context.lineTo(134.13, 196.36);
        context.bezierCurveTo(134.05, 196.36, 133.97, 196.36, 133.89, 196.36);
        context.lineTo(133.89, 196.36);
        context.bezierCurveTo(132.28, 196.36, 131.42, 196.23, 131.63, 194.59);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(66.05, 135.21, 289.77, 290.5));
        context.fill();


        context.restore();



        //// Group 4
        context.save();

        //// Clip Clip 4

        context.beginPath();
        context.moveTo(169.9, 176.75);
        context.lineTo(164.68, 193.4);
        context.bezierCurveTo(164.42, 194.28, 164.2, 195.08, 164.1, 195.81);
        context.lineTo(164.1, 195.81);
        context.bezierCurveTo(163.6, 199.56, 165.49, 201.4, 169.91, 201.38);
        context.lineTo(169.91, 201.38);
        context.lineTo(188.87, 201.26);
        context.lineTo(190.55, 195.97);
        context.lineTo(172.83, 196.08);
        context.bezierCurveTo(171.15, 196.09, 170.15, 195.99, 170.38, 194.28);
        context.lineTo(170.38, 194.28);
        context.bezierCurveTo(170.43, 193.88, 170.57, 193.4, 170.76, 192.78);
        context.lineTo(170.76, 192.78);
        context.lineTo(175.79, 176.71);
        context.lineTo(169.9, 176.75);
        context.closePath();
        context.clip();



        //// Bezier 10 Drawing
        context.beginPath();
        context.moveTo(169.9, 176.75);
        context.lineTo(164.68, 193.4);
        context.bezierCurveTo(164.42, 194.28, 164.2, 195.08, 164.1, 195.81);
        context.lineTo(164.1, 195.81);
        context.bezierCurveTo(163.6, 199.56, 165.49, 201.4, 169.91, 201.38);
        context.lineTo(169.91, 201.38);
        context.lineTo(188.87, 201.26);
        context.lineTo(190.55, 195.97);
        context.lineTo(172.83, 196.08);
        context.bezierCurveTo(171.15, 196.09, 170.15, 195.99, 170.38, 194.28);
        context.lineTo(170.38, 194.28);
        context.bezierCurveTo(170.43, 193.88, 170.57, 193.4, 170.76, 192.78);
        context.lineTo(170.76, 192.78);
        context.lineTo(175.79, 176.71);
        context.lineTo(169.9, 176.75);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(75.09, 122.18, 298.81, 277.47));
        context.fill();


        context.restore();



        //// Group 5
        context.save();

        //// Clip Clip 5

        context.beginPath();
        context.moveTo(227.76, 176.42);
        context.lineTo(186.25, 176.57);
        context.lineTo(184.61, 181.78);
        context.lineTo(224.96, 181.67);
        context.bezierCurveTo(227.17, 181.66, 228.11, 181.91, 227.85, 183.87);
        context.lineTo(227.85, 183.87);
        context.bezierCurveTo(227.77, 184.49, 227.59, 185.26, 227.27, 186.24);
        context.lineTo(227.27, 186.24);
        context.lineTo(225.45, 192.07);
        context.bezierCurveTo(224.61, 194.7, 222.7, 195.8, 219.62, 195.82);
        context.lineTo(219.62, 195.82);
        context.lineTo(202.75, 195.92);
        context.lineTo(205.91, 185.85);
        context.lineTo(199.99, 185.92);
        context.lineTo(195.18, 201.24);
        context.lineTo(220.01, 201.09);
        context.bezierCurveTo(225.67, 201.06, 229.52, 197.76, 231.16, 192.51);
        context.lineTo(231.16, 192.51);
        context.lineTo(233.5, 185.04);
        context.bezierCurveTo(233.76, 184.24, 233.94, 183.47, 234.03, 182.78);
        context.lineTo(234.03, 182.78);
        context.bezierCurveTo(234.56, 178.8, 232.55, 176.42, 227.84, 176.42);
        context.lineTo(227.84, 176.42);
        context.bezierCurveTo(227.81, 176.42, 227.79, 176.42, 227.76, 176.42);
        context.closePath();
        context.clip();



        //// Bezier 12 Drawing
        context.beginPath();
        context.moveTo(227.76, 176.42);
        context.lineTo(186.25, 176.57);
        context.lineTo(184.61, 181.78);
        context.lineTo(224.96, 181.67);
        context.bezierCurveTo(227.17, 181.66, 228.11, 181.91, 227.85, 183.87);
        context.lineTo(227.85, 183.87);
        context.bezierCurveTo(227.77, 184.49, 227.59, 185.26, 227.27, 186.24);
        context.lineTo(227.27, 186.24);
        context.lineTo(225.45, 192.07);
        context.bezierCurveTo(224.61, 194.7, 222.7, 195.8, 219.62, 195.82);
        context.lineTo(219.62, 195.82);
        context.lineTo(202.75, 195.92);
        context.lineTo(205.91, 185.85);
        context.lineTo(199.99, 185.92);
        context.lineTo(195.18, 201.24);
        context.lineTo(220.01, 201.09);
        context.bezierCurveTo(225.67, 201.06, 229.52, 197.76, 231.16, 192.51);
        context.lineTo(231.16, 192.51);
        context.lineTo(233.5, 185.04);
        context.bezierCurveTo(233.76, 184.24, 233.94, 183.47, 234.03, 182.78);
        context.lineTo(234.03, 182.78);
        context.bezierCurveTo(234.56, 178.8, 232.55, 176.42, 227.84, 176.42);
        context.lineTo(227.84, 176.42);
        context.bezierCurveTo(227.81, 176.42, 227.79, 176.42, 227.76, 176.42);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(88.68, 102.6, 312.4, 257.89));
        context.fill();


        context.restore();



        //// Group 6
        context.save();

        //// Clip Clip 6

        context.beginPath();
        context.moveTo(111.73, 210.84);
        context.lineTo(83.11, 211.01);
        context.lineTo(76.38, 232.44);
        context.lineTo(81.94, 232.41);
        context.lineTo(87.12, 215.98);
        context.lineTo(96.55, 215.92);
        context.lineTo(91.38, 232.35);
        context.lineTo(96.91, 232.31);
        context.lineTo(102.09, 215.89);
        context.lineTo(109.31, 215.84);
        context.bezierCurveTo(110.07, 215.84, 110.66, 215.89, 110.91, 216.17);
        context.lineTo(110.91, 216.17);
        context.bezierCurveTo(111.08, 216.36, 111.12, 216.68, 111.06, 217.14);
        context.lineTo(111.06, 217.14);
        context.bezierCurveTo(111.01, 217.52, 110.92, 217.9, 110.78, 218.3);
        context.lineTo(110.78, 218.3);
        context.lineTo(106.38, 232.26);
        context.lineTo(111.95, 232.22);
        context.lineTo(116.46, 217.94);
        context.bezierCurveTo(116.68, 217.21, 116.84, 216.55, 116.92, 215.92);
        context.lineTo(116.92, 215.92);
        context.bezierCurveTo(117.13, 214.35, 116.86, 213.12, 116.11, 212.27);
        context.lineTo(116.11, 212.27);
        context.bezierCurveTo(115.27, 211.31, 113.77, 210.84, 111.74, 210.84);
        context.lineTo(111.74, 210.84);
        context.bezierCurveTo(111.74, 210.84, 111.74, 210.84, 111.73, 210.84);
        context.closePath();
        context.clip();



        //// Bezier 14 Drawing
        context.beginPath();
        context.moveTo(111.73, 210.84);
        context.lineTo(83.11, 211.01);
        context.lineTo(76.38, 232.44);
        context.lineTo(81.94, 232.41);
        context.lineTo(87.12, 215.98);
        context.lineTo(96.55, 215.92);
        context.lineTo(91.38, 232.35);
        context.lineTo(96.91, 232.31);
        context.lineTo(102.09, 215.89);
        context.lineTo(109.31, 215.84);
        context.bezierCurveTo(110.07, 215.84, 110.66, 215.89, 110.91, 216.17);
        context.lineTo(110.91, 216.17);
        context.bezierCurveTo(111.08, 216.36, 111.12, 216.68, 111.06, 217.14);
        context.lineTo(111.06, 217.14);
        context.bezierCurveTo(111.01, 217.52, 110.92, 217.9, 110.78, 218.3);
        context.lineTo(110.78, 218.3);
        context.lineTo(106.38, 232.26);
        context.lineTo(111.95, 232.22);
        context.lineTo(116.46, 217.94);
        context.bezierCurveTo(116.68, 217.21, 116.84, 216.55, 116.92, 215.92);
        context.lineTo(116.92, 215.92);
        context.bezierCurveTo(117.13, 214.35, 116.86, 213.12, 116.11, 212.27);
        context.lineTo(116.11, 212.27);
        context.bezierCurveTo(115.27, 211.31, 113.77, 210.84, 111.74, 210.84);
        context.lineTo(111.74, 210.84);
        context.bezierCurveTo(111.74, 210.84, 111.74, 210.84, 111.73, 210.84);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(35.07, 179.84, 258.79, 335.12));
        context.fill();


        context.restore();



        //// Group 7
        context.save();

        //// Clip Clip 7

        context.beginPath();
        context.moveTo(145.93, 210.63);
        context.lineTo(127.78, 210.74);
        context.bezierCurveTo(124.19, 210.76, 122.03, 212.33, 120.99, 215.68);
        context.lineTo(120.99, 215.68);
        context.lineTo(118.06, 225.05);
        context.bezierCurveTo(117.83, 225.81, 117.67, 226.51, 117.59, 227.13);
        context.lineTo(117.59, 227.13);
        context.bezierCurveTo(117.38, 228.69, 117.65, 229.9, 118.38, 230.74);
        context.lineTo(118.38, 230.74);
        context.bezierCurveTo(119.22, 231.69, 120.63, 232.16, 122.7, 232.16);
        context.lineTo(122.7, 232.16);
        context.lineTo(122.79, 232.16);
        context.lineTo(144.02, 232.03);
        context.lineTo(145.62, 227);
        context.lineTo(125.28, 227.12);
        context.bezierCurveTo(124.48, 227.13, 123.85, 227.11, 123.61, 226.83);
        context.lineTo(123.61, 226.83);
        context.bezierCurveTo(123.46, 226.66, 123.42, 226.36, 123.48, 225.91);
        context.lineTo(123.48, 225.91);
        context.bezierCurveTo(123.53, 225.55, 123.62, 225.15, 123.77, 224.7);
        context.lineTo(123.77, 224.7);
        context.lineTo(124.09, 223.66);
        context.lineTo(142.06, 223.55);
        context.bezierCurveTo(145.62, 223.53, 147.75, 221.95, 148.79, 218.6);
        context.lineTo(148.79, 218.6);
        context.lineTo(149.69, 215.68);
        context.bezierCurveTo(149.88, 215.06, 149.99, 214.61, 150.05, 214.21);
        context.lineTo(150.05, 214.21);
        context.bezierCurveTo(150.19, 213.13, 150, 212.31, 149.48, 211.72);
        context.lineTo(149.48, 211.72);
        context.bezierCurveTo(148.84, 210.99, 147.7, 210.63, 146, 210.63);
        context.lineTo(146, 210.63);
        context.lineTo(145.93, 210.63);
        context.closePath();
        context.moveTo(126.19, 216.96);
        context.bezierCurveTo(126.56, 215.81, 127.18, 215.33, 128.33, 215.33);
        context.lineTo(128.33, 215.33);
        context.lineTo(142.86, 215.24);
        context.lineTo(142.92, 215.24);
        context.bezierCurveTo(143.35, 215.24, 143.79, 215.27, 143.94, 215.44);
        context.lineTo(143.94, 215.44);
        context.bezierCurveTo(144.03, 215.53, 144.06, 215.71, 144.02, 216);
        context.lineTo(144.02, 216);
        context.bezierCurveTo(143.99, 216.21, 143.96, 216.42, 143.87, 216.67);
        context.lineTo(143.87, 216.67);
        context.lineTo(143.49, 217.82);
        context.bezierCurveTo(143.11, 219, 142.49, 219.48, 141.35, 219.49);
        context.lineTo(141.35, 219.49);
        context.lineTo(125.37, 219.59);
        context.lineTo(126.19, 216.96);
        context.closePath();
        context.clip();



        //// Bezier 16 Drawing
        context.beginPath();
        context.moveTo(145.93, 210.63);
        context.lineTo(127.78, 210.74);
        context.bezierCurveTo(124.19, 210.76, 122.03, 212.33, 120.99, 215.68);
        context.lineTo(120.99, 215.68);
        context.lineTo(118.06, 225.05);
        context.bezierCurveTo(117.83, 225.81, 117.67, 226.51, 117.59, 227.13);
        context.lineTo(117.59, 227.13);
        context.bezierCurveTo(117.38, 228.69, 117.65, 229.9, 118.38, 230.74);
        context.lineTo(118.38, 230.74);
        context.bezierCurveTo(119.22, 231.69, 120.63, 232.16, 122.7, 232.16);
        context.lineTo(122.7, 232.16);
        context.lineTo(122.79, 232.16);
        context.lineTo(144.02, 232.03);
        context.lineTo(145.62, 227);
        context.lineTo(125.28, 227.12);
        context.bezierCurveTo(124.48, 227.13, 123.85, 227.11, 123.61, 226.83);
        context.lineTo(123.61, 226.83);
        context.bezierCurveTo(123.46, 226.66, 123.42, 226.36, 123.48, 225.91);
        context.lineTo(123.48, 225.91);
        context.bezierCurveTo(123.53, 225.55, 123.62, 225.15, 123.77, 224.7);
        context.lineTo(123.77, 224.7);
        context.lineTo(124.09, 223.66);
        context.lineTo(142.06, 223.55);
        context.bezierCurveTo(145.62, 223.53, 147.75, 221.95, 148.79, 218.6);
        context.lineTo(148.79, 218.6);
        context.lineTo(149.69, 215.68);
        context.bezierCurveTo(149.88, 215.06, 149.99, 214.61, 150.05, 214.21);
        context.lineTo(150.05, 214.21);
        context.bezierCurveTo(150.19, 213.13, 150, 212.31, 149.48, 211.72);
        context.lineTo(149.48, 211.72);
        context.bezierCurveTo(148.84, 210.99, 147.7, 210.63, 146, 210.63);
        context.lineTo(146, 210.63);
        context.lineTo(145.93, 210.63);
        context.closePath();
        context.moveTo(126.19, 216.96);
        context.bezierCurveTo(126.56, 215.81, 127.18, 215.33, 128.33, 215.33);
        context.lineTo(128.33, 215.33);
        context.lineTo(142.86, 215.24);
        context.lineTo(142.92, 215.24);
        context.bezierCurveTo(143.35, 215.24, 143.79, 215.27, 143.94, 215.44);
        context.lineTo(143.94, 215.44);
        context.bezierCurveTo(144.03, 215.53, 144.06, 215.71, 144.02, 216);
        context.lineTo(144.02, 216);
        context.bezierCurveTo(143.99, 216.21, 143.96, 216.42, 143.87, 216.67);
        context.lineTo(143.87, 216.67);
        context.lineTo(143.49, 217.82);
        context.bezierCurveTo(143.11, 219, 142.49, 219.48, 141.35, 219.49);
        context.lineTo(141.35, 219.49);
        context.lineTo(125.37, 219.59);
        context.lineTo(126.19, 216.96);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(47.82, 161.47, 271.54, 316.76));
        context.fill();


        context.restore();



        //// Group 8
        context.save();

        //// Clip Clip 8

        context.beginPath();
        context.moveTo(176.6, 210.44);
        context.lineTo(155.4, 210.57);
        context.lineTo(148.67, 232);
        context.lineTo(170.05, 231.87);
        context.bezierCurveTo(174.81, 231.84, 178.25, 229.19, 179.74, 224.42);
        context.lineTo(179.74, 224.42);
        context.lineTo(181.72, 218.1);
        context.bezierCurveTo(181.95, 217.4, 182.1, 216.74, 182.18, 216.14);
        context.lineTo(182.18, 216.14);
        context.bezierCurveTo(182.41, 214.4, 182.09, 213.02, 181.23, 212.05);
        context.lineTo(181.23, 212.05);
        context.bezierCurveTo(180.29, 210.98, 178.76, 210.44, 176.67, 210.44);
        context.lineTo(176.67, 210.44);
        context.lineTo(176.6, 210.44);
        context.closePath();
        context.moveTo(159.4, 215.53);
        context.lineTo(174.23, 215.44);
        context.bezierCurveTo(175.26, 215.45, 175.95, 215.5, 176.24, 215.83);
        context.lineTo(176.24, 215.83);
        context.bezierCurveTo(176.43, 216.04, 176.48, 216.41, 176.4, 216.99);
        context.lineTo(176.4, 216.99);
        context.bezierCurveTo(176.33, 217.54, 176.17, 218.17, 175.92, 218.94);
        context.lineTo(175.92, 218.94);
        context.lineTo(174.38, 223.88);
        context.bezierCurveTo(173.73, 225.92, 172.29, 226.83, 169.72, 226.85);
        context.lineTo(169.72, 226.85);
        context.lineTo(155.83, 226.94);
        context.lineTo(159.4, 215.53);
        context.closePath();
        context.clip();



        //// Bezier 18 Drawing
        context.beginPath();
        context.moveTo(176.6, 210.44);
        context.lineTo(155.4, 210.57);
        context.lineTo(148.67, 232);
        context.lineTo(170.05, 231.87);
        context.bezierCurveTo(174.81, 231.84, 178.25, 229.19, 179.74, 224.42);
        context.lineTo(179.74, 224.42);
        context.lineTo(181.72, 218.1);
        context.bezierCurveTo(181.95, 217.4, 182.1, 216.74, 182.18, 216.14);
        context.lineTo(182.18, 216.14);
        context.bezierCurveTo(182.41, 214.4, 182.09, 213.02, 181.23, 212.05);
        context.lineTo(181.23, 212.05);
        context.bezierCurveTo(180.29, 210.98, 178.76, 210.44, 176.67, 210.44);
        context.lineTo(176.67, 210.44);
        context.lineTo(176.6, 210.44);
        context.closePath();
        context.moveTo(159.4, 215.53);
        context.lineTo(174.23, 215.44);
        context.bezierCurveTo(175.26, 215.45, 175.95, 215.5, 176.24, 215.83);
        context.lineTo(176.24, 215.83);
        context.bezierCurveTo(176.43, 216.04, 176.48, 216.41, 176.4, 216.99);
        context.lineTo(176.4, 216.99);
        context.bezierCurveTo(176.33, 217.54, 176.17, 218.17, 175.92, 218.94);
        context.lineTo(175.92, 218.94);
        context.lineTo(174.38, 223.88);
        context.bezierCurveTo(173.73, 225.92, 172.29, 226.83, 169.72, 226.85);
        context.lineTo(169.72, 226.85);
        context.lineTo(155.83, 226.94);
        context.lineTo(159.4, 215.53);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(57.57, 147.42, 281.29, 302.71));
        context.fill();


        context.restore();



        //// Group 9
        context.save();

        //// Clip Clip 9

        context.beginPath();
        context.moveTo(209.78, 210.24);
        context.lineTo(188.51, 210.37);
        context.lineTo(186.96, 215.37);
        context.lineTo(207.32, 215.24);
        context.bezierCurveTo(208.12, 215.24, 208.7, 215.29, 208.95, 215.58);
        context.lineTo(208.95, 215.58);
        context.bezierCurveTo(209.12, 215.76, 209.17, 216.08, 209.1, 216.55);
        context.lineTo(209.1, 216.55);
        context.bezierCurveTo(209.06, 216.91, 208.96, 217.3, 208.83, 217.7);
        context.lineTo(208.83, 217.7);
        context.lineTo(208.46, 218.83);
        context.lineTo(190.45, 218.94);
        context.bezierCurveTo(186.91, 218.96, 184.77, 220.53, 183.73, 223.88);
        context.lineTo(183.73, 223.88);
        context.lineTo(182.84, 226.71);
        context.bezierCurveTo(182.69, 227.17, 182.59, 227.64, 182.52, 228.15);
        context.lineTo(182.52, 228.15);
        context.bezierCurveTo(182.37, 229.25, 182.56, 230.08, 183.09, 230.68);
        context.lineTo(183.09, 230.68);
        context.bezierCurveTo(183.73, 231.41, 184.86, 231.76, 186.53, 231.76);
        context.lineTo(186.53, 231.76);
        context.lineTo(186.6, 231.76);
        context.lineTo(209.96, 231.62);
        context.lineTo(214.47, 217.34);
        context.bezierCurveTo(214.7, 216.59, 214.86, 215.9, 214.94, 215.26);
        context.lineTo(214.94, 215.26);
        context.bezierCurveTo(215.15, 213.7, 214.88, 212.49, 214.15, 211.65);
        context.lineTo(214.15, 211.65);
        context.bezierCurveTo(213.3, 210.7, 211.89, 210.24, 209.82, 210.24);
        context.lineTo(209.82, 210.24);
        context.bezierCurveTo(209.81, 210.24, 209.79, 210.24, 209.78, 210.24);
        context.closePath();
        context.moveTo(188.57, 226.97);
        context.bezierCurveTo(188.5, 226.88, 188.47, 226.7, 188.51, 226.44);
        context.lineTo(188.51, 226.44);
        context.bezierCurveTo(188.54, 226.24, 188.6, 225.97, 188.7, 225.65);
        context.lineTo(188.7, 225.65);
        context.lineTo(189.03, 224.61);
        context.bezierCurveTo(189.4, 223.47, 190.04, 222.98, 191.17, 222.97);
        context.lineTo(191.17, 222.97);
        context.lineTo(207.19, 222.87);
        context.lineTo(205.87, 227.06);
        context.lineTo(189.68, 227.16);
        context.bezierCurveTo(189.22, 227.16, 188.73, 227.14, 188.57, 226.97);
        context.closePath();
        context.clip();



        //// Bezier 20 Drawing
        context.beginPath();
        context.moveTo(209.78, 210.24);
        context.lineTo(188.51, 210.37);
        context.lineTo(186.96, 215.37);
        context.lineTo(207.32, 215.24);
        context.bezierCurveTo(208.12, 215.24, 208.7, 215.29, 208.95, 215.58);
        context.lineTo(208.95, 215.58);
        context.bezierCurveTo(209.12, 215.76, 209.17, 216.08, 209.1, 216.55);
        context.lineTo(209.1, 216.55);
        context.bezierCurveTo(209.06, 216.91, 208.96, 217.3, 208.83, 217.7);
        context.lineTo(208.83, 217.7);
        context.lineTo(208.46, 218.83);
        context.lineTo(190.45, 218.94);
        context.bezierCurveTo(186.91, 218.96, 184.77, 220.53, 183.73, 223.88);
        context.lineTo(183.73, 223.88);
        context.lineTo(182.84, 226.71);
        context.bezierCurveTo(182.69, 227.17, 182.59, 227.64, 182.52, 228.15);
        context.lineTo(182.52, 228.15);
        context.bezierCurveTo(182.37, 229.25, 182.56, 230.08, 183.09, 230.68);
        context.lineTo(183.09, 230.68);
        context.bezierCurveTo(183.73, 231.41, 184.86, 231.76, 186.53, 231.76);
        context.lineTo(186.53, 231.76);
        context.lineTo(186.6, 231.76);
        context.lineTo(209.96, 231.62);
        context.lineTo(214.47, 217.34);
        context.bezierCurveTo(214.7, 216.59, 214.86, 215.9, 214.94, 215.26);
        context.lineTo(214.94, 215.26);
        context.bezierCurveTo(215.15, 213.7, 214.88, 212.49, 214.15, 211.65);
        context.lineTo(214.15, 211.65);
        context.bezierCurveTo(213.3, 210.7, 211.89, 210.24, 209.82, 210.24);
        context.lineTo(209.82, 210.24);
        context.bezierCurveTo(209.81, 210.24, 209.79, 210.24, 209.78, 210.24);
        context.closePath();
        context.moveTo(188.57, 226.97);
        context.bezierCurveTo(188.5, 226.88, 188.47, 226.7, 188.51, 226.44);
        context.lineTo(188.51, 226.44);
        context.bezierCurveTo(188.54, 226.24, 188.6, 225.97, 188.7, 225.65);
        context.lineTo(188.7, 225.65);
        context.lineTo(189.03, 224.61);
        context.bezierCurveTo(189.4, 223.47, 190.04, 222.98, 191.17, 222.97);
        context.lineTo(191.17, 222.97);
        context.lineTo(207.19, 222.87);
        context.lineTo(205.87, 227.06);
        context.lineTo(189.68, 227.16);
        context.bezierCurveTo(189.22, 227.16, 188.73, 227.14, 188.57, 226.97);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(68.9, 131.11, 292.61, 286.4));
        context.fill();


        context.restore();



        //// Group 10
        context.save();

        //// Clip Clip 10

        context.beginPath();
        context.moveTo(220.68, 210.17);
        context.lineTo(216.2, 224.45);
        context.bezierCurveTo(215.99, 225.14, 215.79, 225.86, 215.7, 226.53);
        context.lineTo(215.7, 226.53);
        context.bezierCurveTo(215.49, 228.08, 215.76, 229.3, 216.49, 230.13);
        context.lineTo(216.49, 230.13);
        context.bezierCurveTo(217.34, 231.09, 218.75, 231.56, 220.81, 231.56);
        context.lineTo(220.81, 231.56);
        context.lineTo(220.89, 231.56);
        context.lineTo(236.72, 231.46);
        context.lineTo(238.31, 226.43);
        context.lineTo(223.36, 226.52);
        context.bezierCurveTo(222.6, 226.53, 221.94, 226.51, 221.69, 226.22);
        context.lineTo(221.69, 226.22);
        context.bezierCurveTo(221.54, 226.05, 221.5, 225.75, 221.56, 225.31);
        context.lineTo(221.56, 225.31);
        context.bezierCurveTo(221.6, 225, 221.7, 224.63, 221.87, 224.09);
        context.lineTo(221.87, 224.09);
        context.lineTo(226.24, 210.14);
        context.lineTo(220.68, 210.17);
        context.closePath();
        context.clip();



        //// Bezier 22 Drawing
        context.beginPath();
        context.moveTo(220.68, 210.17);
        context.lineTo(216.2, 224.45);
        context.bezierCurveTo(215.99, 225.14, 215.79, 225.86, 215.7, 226.53);
        context.lineTo(215.7, 226.53);
        context.bezierCurveTo(215.49, 228.08, 215.76, 229.3, 216.49, 230.13);
        context.lineTo(216.49, 230.13);
        context.bezierCurveTo(217.34, 231.09, 218.75, 231.56, 220.81, 231.56);
        context.lineTo(220.81, 231.56);
        context.lineTo(220.89, 231.56);
        context.lineTo(236.72, 231.46);
        context.lineTo(238.31, 226.43);
        context.lineTo(223.36, 226.52);
        context.bezierCurveTo(222.6, 226.53, 221.94, 226.51, 221.69, 226.22);
        context.lineTo(221.69, 226.22);
        context.bezierCurveTo(221.54, 226.05, 221.5, 225.75, 221.56, 225.31);
        context.lineTo(221.56, 225.31);
        context.bezierCurveTo(221.6, 225, 221.7, 224.63, 221.87, 224.09);
        context.lineTo(221.87, 224.09);
        context.lineTo(226.24, 210.14);
        context.lineTo(220.68, 210.17);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(76.74, 119.81, 300.46, 275.09));
        context.fill();


        context.restore();



        //// Group 11
        context.save();

        //// Clip Clip 11

        context.beginPath();
        context.moveTo(76.38, 240.92);
        context.lineTo(71.4, 257.35);
        context.bezierCurveTo(71.12, 258.24, 70.9, 259.06, 70.8, 259.81);
        context.lineTo(70.8, 259.81);
        context.bezierCurveTo(70.29, 263.64, 72.22, 265.53, 76.75, 265.5);
        context.lineTo(76.75, 265.5);
        context.lineTo(93.7, 265.38);
        context.lineTo(95.42, 259.97);
        context.lineTo(79.73, 260.09);
        context.bezierCurveTo(78.01, 260.1, 76.99, 259.99, 77.22, 258.24);
        context.lineTo(77.22, 258.24);
        context.bezierCurveTo(77.27, 257.83, 77.41, 257.35, 77.62, 256.72);
        context.lineTo(77.62, 256.72);
        context.lineTo(82.41, 240.88);
        context.lineTo(76.38, 240.92);
        context.closePath();
        context.clip();



        //// Bezier 24 Drawing
        context.beginPath();
        context.moveTo(76.38, 240.92);
        context.lineTo(71.4, 257.35);
        context.bezierCurveTo(71.12, 258.24, 70.9, 259.06, 70.8, 259.81);
        context.lineTo(70.8, 259.81);
        context.bezierCurveTo(70.29, 263.64, 72.22, 265.53, 76.75, 265.5);
        context.lineTo(76.75, 265.5);
        context.lineTo(93.7, 265.38);
        context.lineTo(95.42, 259.97);
        context.lineTo(79.73, 260.09);
        context.bezierCurveTo(78.01, 260.1, 76.99, 259.99, 77.22, 258.24);
        context.lineTo(77.22, 258.24);
        context.bezierCurveTo(77.27, 257.83, 77.41, 257.35, 77.62, 256.72);
        context.lineTo(77.62, 256.72);
        context.lineTo(82.41, 240.88);
        context.lineTo(76.38, 240.92);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(14.71, 209.18, 238.42, 364.47));
        context.fill();


        context.restore();



        //// Group 12
        context.save();

        //// Clip Clip 12

        context.beginPath();
        context.moveTo(133.24, 240.89);
        context.lineTo(94.13, 241.04);
        context.lineTo(92.51, 246.23);
        context.lineTo(130.36, 246.09);
        context.bezierCurveTo(132.06, 246.08, 133, 246.29, 132.77, 247.98);
        context.lineTo(132.77, 247.98);
        context.bezierCurveTo(132.72, 248.38, 132.62, 248.85, 132.44, 249.39);
        context.lineTo(132.44, 249.39);
        context.lineTo(131.94, 250.94);
        context.lineTo(110.63, 251.07);
        context.bezierCurveTo(106.36, 251.1, 104.17, 253.05, 103.07, 256.62);
        context.lineTo(103.07, 256.62);
        context.lineTo(102.03, 259.94);
        context.bezierCurveTo(101.84, 260.52, 101.73, 261.06, 101.66, 261.56);
        context.lineTo(101.66, 261.56);
        context.bezierCurveTo(101.33, 264.09, 102.56, 265.45, 106.12, 265.42);
        context.lineTo(106.12, 265.42);
        context.lineTo(133.21, 265.26);
        context.lineTo(138.42, 248.78);
        context.bezierCurveTo(138.68, 247.91, 138.86, 247.12, 138.96, 246.4);
        context.lineTo(138.96, 246.4);
        context.bezierCurveTo(139.45, 242.71, 137.64, 240.89, 133.33, 240.89);
        context.lineTo(133.33, 240.89);
        context.bezierCurveTo(133.3, 240.89, 133.27, 240.89, 133.24, 240.89);
        context.closePath();
        context.moveTo(108.03, 259.47);
        context.bezierCurveTo(108.06, 259.22, 108.14, 258.9, 108.27, 258.5);
        context.lineTo(108.27, 258.5);
        context.lineTo(108.65, 257.27);
        context.bezierCurveTo(109.1, 255.9, 109.9, 255.14, 111.46, 255.13);
        context.lineTo(111.46, 255.13);
        context.lineTo(130.65, 255.02);
        context.lineTo(128.91, 260.57);
        context.lineTo(109.72, 260.69);
        context.bezierCurveTo(109.69, 260.69, 109.65, 260.69, 109.62, 260.69);
        context.lineTo(109.62, 260.69);
        context.bezierCurveTo(108.43, 260.69, 107.88, 260.53, 108.03, 259.47);
        context.closePath();
        context.clip();



        //// Bezier 26 Drawing
        context.beginPath();
        context.moveTo(133.24, 240.89);
        context.lineTo(94.13, 241.04);
        context.lineTo(92.51, 246.23);
        context.lineTo(130.36, 246.09);
        context.bezierCurveTo(132.06, 246.08, 133, 246.29, 132.77, 247.98);
        context.lineTo(132.77, 247.98);
        context.bezierCurveTo(132.72, 248.38, 132.62, 248.85, 132.44, 249.39);
        context.lineTo(132.44, 249.39);
        context.lineTo(131.94, 250.94);
        context.lineTo(110.63, 251.07);
        context.bezierCurveTo(106.36, 251.1, 104.17, 253.05, 103.07, 256.62);
        context.lineTo(103.07, 256.62);
        context.lineTo(102.03, 259.94);
        context.bezierCurveTo(101.84, 260.52, 101.73, 261.06, 101.66, 261.56);
        context.lineTo(101.66, 261.56);
        context.bezierCurveTo(101.33, 264.09, 102.56, 265.45, 106.12, 265.42);
        context.lineTo(106.12, 265.42);
        context.lineTo(133.21, 265.26);
        context.lineTo(138.42, 248.78);
        context.bezierCurveTo(138.68, 247.91, 138.86, 247.12, 138.96, 246.4);
        context.lineTo(138.96, 246.4);
        context.bezierCurveTo(139.45, 242.71, 137.64, 240.89, 133.33, 240.89);
        context.lineTo(133.33, 240.89);
        context.bezierCurveTo(133.3, 240.89, 133.27, 240.89, 133.24, 240.89);
        context.closePath();
        context.moveTo(108.03, 259.47);
        context.bezierCurveTo(108.06, 259.22, 108.14, 258.9, 108.27, 258.5);
        context.lineTo(108.27, 258.5);
        context.lineTo(108.65, 257.27);
        context.bezierCurveTo(109.1, 255.9, 109.9, 255.14, 111.46, 255.13);
        context.lineTo(111.46, 255.13);
        context.lineTo(130.65, 255.02);
        context.lineTo(128.91, 260.57);
        context.lineTo(109.72, 260.69);
        context.bezierCurveTo(109.69, 260.69, 109.65, 260.69, 109.62, 260.69);
        context.lineTo(109.62, 260.69);
        context.bezierCurveTo(108.43, 260.69, 107.88, 260.53, 108.03, 259.47);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(28.32, 189.57, 252.04, 344.86));
        context.fill();


        context.restore();



        //// Group 13
        context.save();

        //// Clip Clip 13

        context.beginPath();
        context.moveTo(175.9, 240.63);
        context.lineTo(148.96, 240.79);
        context.lineTo(141.29, 265.21);
        context.lineTo(168.64, 265.04);
        context.bezierCurveTo(172.91, 265.02, 175.06, 263.06, 176.17, 259.49);
        context.lineTo(176.17, 259.49);
        context.lineTo(176.88, 257.22);
        context.bezierCurveTo(177.02, 256.75, 177.12, 256.28, 177.17, 255.88);
        context.lineTo(177.17, 255.88);
        context.bezierCurveTo(177.52, 253.25, 175.74, 252.69, 174.42, 252.55);
        context.lineTo(174.42, 252.55);
        context.bezierCurveTo(175.93, 252.36, 178.32, 251.7, 179.53, 247.66);
        context.lineTo(179.53, 247.66);
        context.lineTo(180, 246.11);
        context.bezierCurveTo(180.15, 245.53, 180.3, 244.96, 180.36, 244.45);
        context.lineTo(180.36, 244.45);
        context.bezierCurveTo(180.69, 241.99, 179.49, 240.63, 175.99, 240.63);
        context.lineTo(175.99, 240.63);
        context.bezierCurveTo(175.96, 240.63, 175.93, 240.63, 175.9, 240.63);
        context.closePath();
        context.moveTo(153.3, 245.48);
        context.lineTo(172.31, 245.37);
        context.bezierCurveTo(173.57, 245.36, 174.18, 245.46, 174.04, 246.54);
        context.lineTo(174.04, 246.54);
        context.bezierCurveTo(174.01, 246.8, 173.93, 247.12, 173.8, 247.48);
        context.lineTo(173.8, 247.48);
        context.lineTo(173.49, 248.45);
        context.bezierCurveTo(172.98, 250.04, 171.87, 250.55, 170.43, 250.56);
        context.lineTo(170.43, 250.56);
        context.lineTo(151.68, 250.68);
        context.lineTo(153.3, 245.48);
        context.closePath();
        context.moveTo(150.34, 254.9);
        context.lineTo(169.38, 254.78);
        context.bezierCurveTo(170.64, 254.77, 171.56, 254.87, 171.38, 256.17);
        context.lineTo(171.38, 256.17);
        context.bezierCurveTo(171.36, 256.35, 171.3, 256.57, 171.22, 256.82);
        context.lineTo(171.22, 256.82);
        context.lineTo(170.83, 258.12);
        context.bezierCurveTo(170.38, 259.56, 169.53, 260.32, 167.97, 260.33);
        context.lineTo(167.97, 260.33);
        context.lineTo(148.6, 260.45);
        context.lineTo(150.34, 254.9);
        context.closePath();
        context.clip();



        //// Bezier 28 Drawing
        context.beginPath();
        context.moveTo(175.9, 240.63);
        context.lineTo(148.96, 240.79);
        context.lineTo(141.29, 265.21);
        context.lineTo(168.64, 265.04);
        context.bezierCurveTo(172.91, 265.02, 175.06, 263.06, 176.17, 259.49);
        context.lineTo(176.17, 259.49);
        context.lineTo(176.88, 257.22);
        context.bezierCurveTo(177.02, 256.75, 177.12, 256.28, 177.17, 255.88);
        context.lineTo(177.17, 255.88);
        context.bezierCurveTo(177.52, 253.25, 175.74, 252.69, 174.42, 252.55);
        context.lineTo(174.42, 252.55);
        context.bezierCurveTo(175.93, 252.36, 178.32, 251.7, 179.53, 247.66);
        context.lineTo(179.53, 247.66);
        context.lineTo(180, 246.11);
        context.bezierCurveTo(180.15, 245.53, 180.3, 244.96, 180.36, 244.45);
        context.lineTo(180.36, 244.45);
        context.bezierCurveTo(180.69, 241.99, 179.49, 240.63, 175.99, 240.63);
        context.lineTo(175.99, 240.63);
        context.bezierCurveTo(175.96, 240.63, 175.93, 240.63, 175.9, 240.63);
        context.closePath();
        context.moveTo(153.3, 245.48);
        context.lineTo(172.31, 245.37);
        context.bezierCurveTo(173.57, 245.36, 174.18, 245.46, 174.04, 246.54);
        context.lineTo(174.04, 246.54);
        context.bezierCurveTo(174.01, 246.8, 173.93, 247.12, 173.8, 247.48);
        context.lineTo(173.8, 247.48);
        context.lineTo(173.49, 248.45);
        context.bezierCurveTo(172.98, 250.04, 171.87, 250.55, 170.43, 250.56);
        context.lineTo(170.43, 250.56);
        context.lineTo(151.68, 250.68);
        context.lineTo(153.3, 245.48);
        context.closePath();
        context.moveTo(150.34, 254.9);
        context.lineTo(169.38, 254.78);
        context.bezierCurveTo(170.64, 254.77, 171.56, 254.87, 171.38, 256.17);
        context.lineTo(171.38, 256.17);
        context.bezierCurveTo(171.36, 256.35, 171.3, 256.57, 171.22, 256.82);
        context.lineTo(171.22, 256.82);
        context.lineTo(170.83, 258.12);
        context.bezierCurveTo(170.38, 259.56, 169.53, 260.32, 167.97, 260.33);
        context.lineTo(167.97, 260.33);
        context.lineTo(148.6, 260.45);
        context.lineTo(150.34, 254.9);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(41.38, 170.75, 265.1, 326.04));
        context.fill();


        context.restore();



        //// Group 14
        context.save();

        //// Clip Clip 14

        context.beginPath();
        context.moveTo(194.04, 240.52);
        context.bezierCurveTo(189.77, 240.54, 187.58, 242.5, 186.47, 246.07);
        context.lineTo(186.47, 246.07);
        context.lineTo(185.5, 249.17);
        context.bezierCurveTo(185.31, 249.75, 185.2, 250.33, 185.14, 250.8);
        context.lineTo(185.14, 250.8);
        context.bezierCurveTo(184.8, 253.35, 186.02, 254.71, 189.58, 254.69);
        context.lineTo(189.58, 254.69);
        context.lineTo(207.7, 254.58);
        context.bezierCurveTo(208.88, 254.57, 209.51, 254.61, 209.37, 255.69);
        context.lineTo(209.37, 255.69);
        context.bezierCurveTo(209.33, 255.97, 209.25, 256.3, 209.12, 256.73);
        context.lineTo(209.12, 256.73);
        context.lineTo(208.78, 257.89);
        context.bezierCurveTo(208.36, 259.33, 207.41, 260.09, 205.92, 260.1);
        context.lineTo(205.92, 260.1);
        context.lineTo(182.02, 260.25);
        context.lineTo(180.54, 264.97);
        context.lineTo(206.55, 264.81);
        context.bezierCurveTo(210.86, 264.78, 213.05, 262.83, 214.16, 259.26);
        context.lineTo(214.16, 259.26);
        context.lineTo(215.2, 255.9);
        context.bezierCurveTo(215.39, 255.29, 215.54, 254.75, 215.61, 254.21);
        context.lineTo(215.61, 254.21);
        context.bezierCurveTo(215.94, 251.72, 214.68, 250.36, 211.11, 250.38);
        context.lineTo(211.11, 250.38);
        context.lineTo(193.04, 250.49);
        context.bezierCurveTo(191.78, 250.5, 191.15, 250.47, 191.3, 249.35);
        context.lineTo(191.3, 249.35);
        context.bezierCurveTo(191.33, 249.1, 191.41, 248.78, 191.54, 248.34);
        context.lineTo(191.54, 248.34);
        context.lineTo(191.86, 247.37);
        context.bezierCurveTo(192.31, 245.96, 193.11, 245.24, 194.67, 245.23);
        context.lineTo(194.67, 245.23);
        context.lineTo(227.99, 245.09);
        context.lineTo(232.38, 240.37);
        context.lineTo(194.04, 240.52);
        context.closePath();
        context.clip();



        //// Bezier 30 Drawing
        context.beginPath();
        context.moveTo(194.04, 240.52);
        context.bezierCurveTo(189.77, 240.54, 187.58, 242.5, 186.47, 246.07);
        context.lineTo(186.47, 246.07);
        context.lineTo(185.5, 249.17);
        context.bezierCurveTo(185.31, 249.75, 185.2, 250.33, 185.14, 250.8);
        context.lineTo(185.14, 250.8);
        context.bezierCurveTo(184.8, 253.35, 186.02, 254.71, 189.58, 254.69);
        context.lineTo(189.58, 254.69);
        context.lineTo(207.7, 254.58);
        context.bezierCurveTo(208.88, 254.57, 209.51, 254.61, 209.37, 255.69);
        context.lineTo(209.37, 255.69);
        context.bezierCurveTo(209.33, 255.97, 209.25, 256.3, 209.12, 256.73);
        context.lineTo(209.12, 256.73);
        context.lineTo(208.78, 257.89);
        context.bezierCurveTo(208.36, 259.33, 207.41, 260.09, 205.92, 260.1);
        context.lineTo(205.92, 260.1);
        context.lineTo(182.02, 260.25);
        context.lineTo(180.54, 264.97);
        context.lineTo(206.55, 264.81);
        context.bezierCurveTo(210.86, 264.78, 213.05, 262.83, 214.16, 259.26);
        context.lineTo(214.16, 259.26);
        context.lineTo(215.2, 255.9);
        context.bezierCurveTo(215.39, 255.29, 215.54, 254.75, 215.61, 254.21);
        context.lineTo(215.61, 254.21);
        context.bezierCurveTo(215.94, 251.72, 214.68, 250.36, 211.11, 250.38);
        context.lineTo(211.11, 250.38);
        context.lineTo(193.04, 250.49);
        context.bezierCurveTo(191.78, 250.5, 191.15, 250.47, 191.3, 249.35);
        context.lineTo(191.3, 249.35);
        context.bezierCurveTo(191.33, 249.1, 191.41, 248.78, 191.54, 248.34);
        context.lineTo(191.54, 248.34);
        context.lineTo(191.86, 247.37);
        context.bezierCurveTo(192.31, 245.96, 193.11, 245.24, 194.67, 245.23);
        context.lineTo(194.67, 245.23);
        context.lineTo(227.99, 245.09);
        context.lineTo(232.38, 240.37);
        context.lineTo(194.04, 240.52);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(56.68, 148.71, 280.4, 303.99));
        context.fill();


        context.restore();



        //// Group 15
        context.save();

        //// Clip Clip 15

        context.beginPath();
        context.moveTo(99.74, 177.02);
        context.bezierCurveTo(94.41, 177.06, 91.13, 179.73, 89.44, 185.09);
        context.lineTo(89.44, 185.09);
        context.lineTo(86.25, 195.22);
        context.bezierCurveTo(85.99, 196.1, 85.77, 196.86, 85.68, 197.55);
        context.lineTo(85.68, 197.55);
        context.bezierCurveTo(85.29, 200.47, 86.62, 201.73, 90.15, 201.71);
        context.lineTo(90.15, 201.71);
        context.lineTo(117.23, 201.54);
        context.lineTo(121.46, 188.09);
        context.lineTo(108.93, 188.14);
        context.lineTo(107.29, 192.88);
        context.lineTo(114.11, 192.88);
        context.lineTo(112.88, 196.8);
        context.lineTo(93.78, 196.92);
        context.bezierCurveTo(92.55, 196.93, 91.92, 196.86, 92.08, 195.66);
        context.lineTo(92.08, 195.66);
        context.bezierCurveTo(92.12, 195.33, 92.22, 194.93, 92.4, 194.42);
        context.lineTo(92.4, 194.42);
        context.lineTo(95.18, 185.64);
        context.bezierCurveTo(95.89, 183.38, 97.2, 182.28, 99.38, 182.26);
        context.lineTo(99.38, 182.26);
        context.lineTo(122.74, 182.12);
        context.lineTo(124.38, 176.87);
        context.lineTo(99.74, 177.02);
        context.closePath();
        context.clip();



        //// Bezier 32 Drawing
        context.beginPath();
        context.moveTo(99.74, 177.02);
        context.bezierCurveTo(94.41, 177.06, 91.13, 179.73, 89.44, 185.09);
        context.lineTo(89.44, 185.09);
        context.lineTo(86.25, 195.22);
        context.bezierCurveTo(85.99, 196.1, 85.77, 196.86, 85.68, 197.55);
        context.lineTo(85.68, 197.55);
        context.bezierCurveTo(85.29, 200.47, 86.62, 201.73, 90.15, 201.71);
        context.lineTo(90.15, 201.71);
        context.lineTo(117.23, 201.54);
        context.lineTo(121.46, 188.09);
        context.lineTo(108.93, 188.14);
        context.lineTo(107.29, 192.88);
        context.lineTo(114.11, 192.88);
        context.lineTo(112.88, 196.8);
        context.lineTo(93.78, 196.92);
        context.bezierCurveTo(92.55, 196.93, 91.92, 196.86, 92.08, 195.66);
        context.lineTo(92.08, 195.66);
        context.bezierCurveTo(92.12, 195.33, 92.22, 194.93, 92.4, 194.42);
        context.lineTo(92.4, 194.42);
        context.lineTo(95.18, 185.64);
        context.bezierCurveTo(95.89, 183.38, 97.2, 182.28, 99.38, 182.26);
        context.lineTo(99.38, 182.26);
        context.lineTo(122.74, 182.12);
        context.lineTo(124.38, 176.87);
        context.lineTo(99.74, 177.02);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(53.74, 152.95, 277.45, 308.23));
        context.fill();


        context.restore();



        //// Group 16
        context.save();

        //// Clip Clip 16

        context.beginPath();
        context.moveTo(266, 214.48);
        context.lineTo(265.24, 214.56);
        context.lineTo(264.82, 215.79);
        context.lineTo(258.76, 233.51);
        context.lineTo(258.56, 234.1);
        context.lineTo(258.69, 234.7);
        context.lineTo(259.89, 240.26);
        context.lineTo(253.66, 240.36);
        context.lineTo(237.54, 259.59);
        context.lineTo(231.22, 259.59);
        context.lineTo(251.87, 235.69);
        context.lineTo(252.14, 235.38);
        context.lineTo(252.28, 235);
        context.lineTo(256.22, 224.36);
        context.lineTo(251.42, 224.43);
        context.lineTo(248.24, 233.09);
        context.lineTo(224.67, 260.36);
        context.lineTo(223.62, 261.58);
        context.bezierCurveTo(222.79, 262.54, 223.47, 264.04, 224.75, 264.04);
        context.lineTo(224.75, 264.04);
        context.lineTo(226.36, 264.04);
        context.lineTo(266.81, 264.04);
        context.lineTo(267.72, 264.04);
        context.bezierCurveTo(268.67, 264.04, 269.38, 263.17, 269.18, 262.24);
        context.lineTo(269.18, 262.24);
        context.lineTo(268.99, 261.35);
        context.lineTo(263.17, 234.37);
        context.lineTo(268.93, 217.52);
        context.lineTo(271.62, 215);
        context.lineTo(271.14, 213.95);
        context.lineTo(266, 214.48);
        context.closePath();
        context.clip();



        //// Bezier 34 Drawing
        context.beginPath();
        context.moveTo(266, 214.48);
        context.lineTo(265.24, 214.56);
        context.lineTo(264.82, 215.79);
        context.lineTo(258.76, 233.51);
        context.lineTo(258.56, 234.1);
        context.lineTo(258.69, 234.7);
        context.lineTo(259.89, 240.26);
        context.lineTo(253.66, 240.36);
        context.lineTo(237.54, 259.59);
        context.lineTo(231.22, 259.59);
        context.lineTo(251.87, 235.69);
        context.lineTo(252.14, 235.38);
        context.lineTo(252.28, 235);
        context.lineTo(256.22, 224.36);
        context.lineTo(251.42, 224.43);
        context.lineTo(248.24, 233.09);
        context.lineTo(224.67, 260.36);
        context.lineTo(223.62, 261.58);
        context.bezierCurveTo(222.79, 262.54, 223.47, 264.04, 224.75, 264.04);
        context.lineTo(224.75, 264.04);
        context.lineTo(226.36, 264.04);
        context.lineTo(266.81, 264.04);
        context.lineTo(267.72, 264.04);
        context.bezierCurveTo(268.67, 264.04, 269.38, 263.17, 269.18, 262.24);
        context.lineTo(269.18, 262.24);
        context.lineTo(268.99, 261.35);
        context.lineTo(263.17, 234.37);
        context.lineTo(268.93, 217.52);
        context.lineTo(271.62, 215);
        context.lineTo(271.14, 213.95);
        context.lineTo(266, 214.48);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(76.5, 120.16, 300.22, 275.44));
        context.fill();


        context.restore();



        //// Group 17
        context.save();

        //// Clip Clip 17

        context.beginPath();
        context.moveTo(249.85, 170.88);
        context.lineTo(239.94, 170.78);
        context.lineTo(247.08, 176.69);
        context.lineTo(242.6, 186.1);
        context.lineTo(251.49, 180.35);
        context.lineTo(258.63, 186.26);
        context.lineTo(256.98, 176.79);
        context.lineTo(265.88, 171.04);
        context.lineTo(255.97, 170.94);
        context.lineTo(254.33, 161.48);
        context.lineTo(249.85, 170.88);
        context.closePath();
        context.clip();



        //// Bezier 36 Drawing
        context.beginPath();
        context.moveTo(249.85, 170.88);
        context.lineTo(239.94, 170.78);
        context.lineTo(247.08, 176.69);
        context.lineTo(242.6, 186.1);
        context.lineTo(251.49, 180.35);
        context.lineTo(258.63, 186.26);
        context.lineTo(256.98, 176.79);
        context.lineTo(265.88, 171.04);
        context.lineTo(255.97, 170.94);
        context.lineTo(254.33, 161.48);
        context.lineTo(249.85, 170.88);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(107.29, 75.8, 331.01, 231.08));
        context.fill();


        context.restore();



        //// Group 18
        context.save();

        //// Clip Clip 18

        context.beginPath();
        context.moveTo(263.89, 196.47);
        context.lineTo(258.11, 196.41);
        context.lineTo(262.28, 199.86);
        context.lineTo(259.66, 205.35);
        context.lineTo(264.85, 201.99);
        context.lineTo(269.02, 205.44);
        context.lineTo(268.06, 199.92);
        context.lineTo(273.25, 196.56);
        context.lineTo(267.47, 196.51);
        context.lineTo(266.51, 190.98);
        context.lineTo(263.89, 196.47);
        context.closePath();
        context.clip();



        //// Bezier 38 Drawing
        context.beginPath();
        context.moveTo(263.89, 196.47);
        context.lineTo(258.11, 196.41);
        context.lineTo(262.28, 199.86);
        context.lineTo(259.66, 205.35);
        context.lineTo(264.85, 201.99);
        context.lineTo(269.02, 205.44);
        context.lineTo(268.06, 199.92);
        context.lineTo(273.25, 196.56);
        context.lineTo(267.47, 196.51);
        context.lineTo(266.51, 190.98);
        context.lineTo(263.89, 196.47);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(100.63, 85.4, 324.34, 240.68));
        context.fill();


        context.restore();



        //// Group 19
        context.save();

        //// Clip Clip 19

        context.beginPath();
        context.moveTo(253.78, 212.25);
        context.lineTo(249.79, 212.21);
        context.lineTo(252.66, 214.59);
        context.lineTo(250.86, 218.37);
        context.lineTo(254.44, 216.06);
        context.lineTo(257.31, 218.44);
        context.lineTo(256.65, 214.63);
        context.lineTo(260.23, 212.31);
        context.lineTo(256.24, 212.27);
        context.lineTo(255.58, 208.46);
        context.lineTo(253.78, 212.25);
        context.closePath();
        context.clip();



        //// Bezier 40 Drawing
        context.beginPath();
        context.moveTo(253.78, 212.25);
        context.lineTo(249.79, 212.21);
        context.lineTo(252.66, 214.59);
        context.lineTo(250.86, 218.37);
        context.lineTo(254.44, 216.06);
        context.lineTo(257.31, 218.44);
        context.lineTo(256.65, 214.63);
        context.lineTo(260.23, 212.31);
        context.lineTo(256.24, 212.27);
        context.lineTo(255.58, 208.46);
        context.lineTo(253.78, 212.25);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(90.28, 100.32, 313.99, 255.6));
        context.fill();


        context.restore();



        //// Group 20
        context.save();

        //// Clip Clip 20

        context.beginPath();
        context.moveTo(164.89, 126.99);
        context.lineTo(143.26, 126.78);
        context.lineTo(158.84, 139.68);
        context.lineTo(149.06, 160.22);
        context.lineTo(168.47, 147.66);
        context.lineTo(184.06, 160.56);
        context.lineTo(180.47, 139.9);
        context.lineTo(199.88, 127.34);
        context.lineTo(178.25, 127.13);
        context.lineTo(174.67, 106.46);
        context.lineTo(164.89, 126.99);
        context.closePath();
        context.clip();



        //// Bezier 42 Drawing
        context.beginPath();
        context.moveTo(164.89, 126.99);
        context.lineTo(143.26, 126.78);
        context.lineTo(158.84, 139.68);
        context.lineTo(149.06, 160.22);
        context.lineTo(168.47, 147.66);
        context.lineTo(184.06, 160.56);
        context.lineTo(180.47, 139.9);
        context.lineTo(199.88, 127.34);
        context.lineTo(178.25, 127.13);
        context.lineTo(174.67, 106.46);
        context.lineTo(164.89, 126.99);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(98.08, 89.07, 321.8, 244.35));
        context.fill();


        context.restore();



        //// Group 21
        context.save();

        //// Clip Clip 21

        context.beginPath();
        context.moveTo(220.22, 142.04);
        context.lineTo(207.93, 141.92);
        context.lineTo(216.78, 149.26);
        context.lineTo(211.22, 160.93);
        context.lineTo(222.25, 153.79);
        context.lineTo(231.11, 161.12);
        context.lineTo(229.07, 149.38);
        context.lineTo(240.11, 142.24);
        context.lineTo(227.81, 142.12);
        context.lineTo(225.78, 130.38);
        context.lineTo(220.22, 142.04);
        context.closePath();
        context.clip();



        //// Bezier 44 Drawing
        context.beginPath();
        context.moveTo(220.22, 142.04);
        context.lineTo(207.93, 141.92);
        context.lineTo(216.78, 149.26);
        context.lineTo(211.22, 160.93);
        context.lineTo(222.25, 153.79);
        context.lineTo(231.11, 161.12);
        context.lineTo(229.07, 149.38);
        context.lineTo(240.11, 142.24);
        context.lineTo(227.81, 142.12);
        context.lineTo(225.78, 130.38);
        context.lineTo(220.22, 142.04);
        context.closePath();
        context.fillStyle = gradient2(context.createLinearGradient(110.73, 70.85, 334.45, 226.13));
        context.fill();


        context.restore();



        //// Bezier 46 Drawing
        context.beginPath();
        context.moveTo(82.32, 292.71);
        context.bezierCurveTo(82.32, 292.51, 82.36, 292.32, 82.42, 292.1);
        context.lineTo(82.68, 291.21);
        context.lineTo(84.89, 291.21);
        context.lineTo(84.68, 291.9);
        context.bezierCurveTo(84.65, 292.02, 84.62, 292.13, 84.62, 292.24);
        context.bezierCurveTo(84.61, 292.93, 85.32, 293.27, 86.39, 293.27);
        context.bezierCurveTo(87.6, 293.27, 88.61, 292.82, 88.83, 291.94);
        context.lineTo(88.92, 291.65);
        context.bezierCurveTo(88.96, 291.46, 88.99, 291.29, 88.99, 291.16);
        context.bezierCurveTo(89, 290.72, 88.69, 290.5, 87.96, 290.47);
        context.lineTo(85.86, 290.4);
        context.bezierCurveTo(84.16, 290.36, 83.4, 289.91, 83.42, 288.87);
        context.bezierCurveTo(83.42, 288.62, 83.47, 288.37, 83.56, 288.07);
        context.lineTo(83.72, 287.49);
        context.bezierCurveTo(84.29, 285.38, 86.62, 284.76, 88.76, 284.76);
        context.bezierCurveTo(90.74, 284.76, 92.48, 285.25, 92.45, 286.71);
        context.bezierCurveTo(92.45, 286.9, 92.4, 287.11, 92.34, 287.33);
        context.lineTo(92.1, 288.19);
        context.lineTo(89.89, 288.19);
        context.lineTo(90.08, 287.55);
        context.bezierCurveTo(90.1, 287.41, 90.13, 287.29, 90.13, 287.17);
        context.bezierCurveTo(90.15, 286.46, 89.45, 286.13, 88.38, 286.13);
        context.bezierCurveTo(87.17, 286.13, 86.17, 286.57, 85.93, 287.49);
        context.lineTo(85.86, 287.78);
        context.bezierCurveTo(85.81, 287.94, 85.78, 288.1, 85.78, 288.22);
        context.bezierCurveTo(85.77, 288.73, 86.1, 288.96, 86.81, 288.98);
        context.lineTo(88.91, 289.04);
        context.bezierCurveTo(90.64, 289.1, 91.39, 289.55, 91.37, 290.48);
        context.bezierCurveTo(91.37, 290.7, 91.34, 290.94, 91.25, 291.21);
        context.lineTo(91.04, 291.95);
        context.bezierCurveTo(90.47, 294.01, 88.15, 294.63, 86.01, 294.63);
        context.bezierCurveTo(84.02, 294.63, 82.29, 294.14, 82.32, 292.71);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 47 Drawing
        context.beginPath();
        context.moveTo(101.35, 287.26);
        context.bezierCurveTo(101.37, 286.6, 100.96, 286.27, 99.67, 286.27);
        context.lineTo(97.71, 286.27);
        context.lineTo(96.62, 290.06);
        context.lineTo(98.59, 290.07);
        context.bezierCurveTo(100.31, 290.09, 100.84, 289.48, 101.14, 288.33);
        context.lineTo(101.22, 288.03);
        context.bezierCurveTo(101.3, 287.73, 101.35, 287.48, 101.35, 287.26);
        context.closePath();
        context.moveTo(103.69, 286.79);
        context.bezierCurveTo(103.68, 287.05, 103.62, 287.35, 103.53, 287.68);
        context.lineTo(103.25, 288.66);
        context.bezierCurveTo(102.68, 290.72, 101.08, 291.47, 98.19, 291.46);
        context.lineTo(96.23, 291.44);
        context.lineTo(95.35, 294.52);
        context.lineTo(93.14, 294.52);
        context.lineTo(95.89, 284.91);
        context.lineTo(100.07, 284.91);
        context.bezierCurveTo(102.49, 284.9, 103.71, 285.43, 103.69, 286.79);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 48 Drawing
        context.beginPath();
        context.moveTo(111.38, 291.07);
        context.lineTo(112.18, 288.33);
        context.bezierCurveTo(112.29, 287.87, 112.38, 287.5, 112.39, 287.2);
        context.bezierCurveTo(112.4, 286.45, 111.96, 286.13, 110.73, 286.13);
        context.bezierCurveTo(109, 286.13, 108.47, 286.75, 108.02, 288.33);
        context.lineTo(107.24, 291.07);
        context.bezierCurveTo(107.11, 291.53, 107.03, 291.9, 107.03, 292.21);
        context.bezierCurveTo(107.01, 292.95, 107.45, 293.27, 108.68, 293.27);
        context.bezierCurveTo(110.41, 293.27, 110.95, 292.65, 111.38, 291.07);
        context.closePath();
        context.moveTo(104.7, 292.64);
        context.bezierCurveTo(104.7, 292.31, 104.78, 291.94, 104.9, 291.51);
        context.lineTo(105.94, 287.9);
        context.bezierCurveTo(106.62, 285.51, 108.21, 284.77, 111.11, 284.77);
        context.bezierCurveTo(113.5, 284.77, 114.73, 285.28, 114.7, 286.78);
        context.bezierCurveTo(114.7, 287.09, 114.64, 287.48, 114.5, 287.9);
        context.lineTo(113.48, 291.51);
        context.bezierCurveTo(112.79, 293.89, 111.19, 294.64, 108.29, 294.64);
        context.bezierCurveTo(105.91, 294.64, 104.67, 294.14, 104.7, 292.64);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 49 Drawing
        context.beginPath();
        context.moveTo(123.73, 287.23);
        context.bezierCurveTo(123.74, 286.61, 123.32, 286.27, 122.02, 286.27);
        context.lineTo(120.06, 286.27);
        context.lineTo(119.03, 289.86);
        context.lineTo(120.98, 289.88);
        context.bezierCurveTo(122.71, 289.89, 123.21, 289.26, 123.52, 288.21);
        context.lineTo(123.59, 287.93);
        context.bezierCurveTo(123.68, 287.67, 123.73, 287.43, 123.73, 287.23);
        context.closePath();
        context.moveTo(126.03, 286.79);
        context.bezierCurveTo(126.03, 287.05, 125.97, 287.35, 125.88, 287.68);
        context.lineTo(125.66, 288.45);
        context.bezierCurveTo(125.28, 289.81, 124.44, 290.6, 123.06, 290.98);
        context.lineTo(124.41, 294.52);
        context.lineTo(121.98, 294.52);
        context.lineTo(120.73, 291.25);
        context.lineTo(120.6, 291.25);
        context.lineTo(118.64, 291.24);
        context.lineTo(117.7, 294.52);
        context.lineTo(115.49, 294.52);
        context.lineTo(118.24, 284.91);
        context.lineTo(122.41, 284.91);
        context.bezierCurveTo(124.84, 284.89, 126.06, 285.43, 126.03, 286.79);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 50 Drawing
        context.beginPath();
        context.moveTo(137.04, 286.46);
        context.lineTo(133.86, 286.46);
        context.lineTo(131.55, 294.52);
        context.lineTo(129.33, 294.52);
        context.lineTo(131.65, 286.46);
        context.lineTo(128.46, 286.46);
        context.lineTo(128.92, 284.91);
        context.lineTo(137.48, 284.91);
        context.lineTo(137.04, 286.46);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 51 Drawing
        context.beginPath();
        context.moveTo(137.46, 292.71);
        context.bezierCurveTo(137.47, 292.51, 137.5, 292.32, 137.56, 292.1);
        context.lineTo(137.82, 291.21);
        context.lineTo(140.03, 291.21);
        context.lineTo(139.83, 291.9);
        context.bezierCurveTo(139.8, 292.02, 139.77, 292.13, 139.77, 292.24);
        context.bezierCurveTo(139.75, 292.93, 140.46, 293.27, 141.53, 293.27);
        context.bezierCurveTo(142.74, 293.27, 143.75, 292.82, 143.98, 291.94);
        context.lineTo(144.06, 291.65);
        context.bezierCurveTo(144.11, 291.46, 144.13, 291.29, 144.14, 291.16);
        context.bezierCurveTo(144.15, 290.72, 143.83, 290.5, 143.1, 290.47);
        context.lineTo(141.01, 290.4);
        context.bezierCurveTo(139.3, 290.36, 138.54, 289.91, 138.56, 288.87);
        context.bezierCurveTo(138.57, 288.62, 138.61, 288.37, 138.7, 288.07);
        context.lineTo(138.86, 287.49);
        context.bezierCurveTo(139.43, 285.38, 141.77, 284.76, 143.91, 284.76);
        context.bezierCurveTo(145.88, 284.76, 147.62, 285.25, 147.59, 286.71);
        context.bezierCurveTo(147.59, 286.9, 147.55, 287.11, 147.49, 287.33);
        context.lineTo(147.24, 288.19);
        context.lineTo(145.03, 288.19);
        context.lineTo(145.22, 287.55);
        context.bezierCurveTo(145.25, 287.41, 145.28, 287.29, 145.28, 287.17);
        context.bezierCurveTo(145.29, 286.46, 144.6, 286.13, 143.53, 286.13);
        context.bezierCurveTo(142.32, 286.13, 141.31, 286.57, 141.07, 287.49);
        context.lineTo(141, 287.78);
        context.bezierCurveTo(140.95, 287.94, 140.93, 288.1, 140.92, 288.22);
        context.bezierCurveTo(140.92, 288.73, 141.24, 288.96, 141.95, 288.98);
        context.lineTo(144.05, 289.04);
        context.bezierCurveTo(145.78, 289.1, 146.53, 289.55, 146.51, 290.48);
        context.bezierCurveTo(146.51, 290.7, 146.48, 290.94, 146.39, 291.21);
        context.lineTo(146.19, 291.95);
        context.bezierCurveTo(145.61, 294.01, 143.29, 294.63, 141.15, 294.63);
        context.bezierCurveTo(139.16, 294.63, 137.44, 294.14, 137.46, 292.71);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 52 Drawing
        context.beginPath();
        context.moveTo(164.83, 284.91);
        context.lineTo(162.08, 294.52);
        context.lineTo(160.01, 294.52);
        context.lineTo(157.22, 288.19);
        context.lineTo(155.4, 294.52);
        context.lineTo(153.5, 294.52);
        context.lineTo(156.24, 284.91);
        context.lineTo(158.22, 284.91);
        context.lineTo(161.02, 291.57);
        context.lineTo(162.92, 284.91);
        context.lineTo(164.83, 284.91);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 53 Drawing
        context.beginPath();
        context.moveTo(165.71, 292.62);
        context.bezierCurveTo(165.72, 292.31, 165.79, 291.94, 165.91, 291.51);
        context.lineTo(167.78, 284.91);
        context.lineTo(169.99, 284.91);
        context.lineTo(168.24, 291.09);
        context.bezierCurveTo(168.11, 291.54, 168.03, 291.91, 168.03, 292.21);
        context.bezierCurveTo(168.01, 292.97, 168.44, 293.27, 169.68, 293.27);
        context.bezierCurveTo(171.41, 293.27, 171.94, 292.65, 172.4, 291.09);
        context.lineTo(174.16, 284.91);
        context.lineTo(176.37, 284.91);
        context.lineTo(174.49, 291.51);
        context.bezierCurveTo(173.82, 293.89, 172.2, 294.64, 169.3, 294.64);
        context.bezierCurveTo(166.92, 294.64, 165.68, 294.14, 165.71, 292.62);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 54 Drawing
        context.beginPath();
        context.moveTo(186.72, 286.46);
        context.lineTo(183.54, 286.46);
        context.lineTo(181.23, 294.52);
        context.lineTo(179.01, 294.52);
        context.lineTo(181.33, 286.46);
        context.lineTo(178.14, 286.46);
        context.lineTo(178.59, 284.91);
        context.lineTo(187.16, 284.91);
        context.lineTo(186.72, 286.46);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 55 Drawing
        context.beginPath();
        context.moveTo(194.95, 287.23);
        context.bezierCurveTo(194.96, 286.61, 194.54, 286.27, 193.24, 286.27);
        context.lineTo(191.28, 286.27);
        context.lineTo(190.25, 289.86);
        context.lineTo(192.2, 289.88);
        context.bezierCurveTo(193.93, 289.89, 194.44, 289.26, 194.74, 288.21);
        context.lineTo(194.82, 287.93);
        context.bezierCurveTo(194.9, 287.67, 194.95, 287.43, 194.95, 287.23);
        context.closePath();
        context.moveTo(197.25, 286.79);
        context.bezierCurveTo(197.25, 287.05, 197.19, 287.35, 197.1, 287.68);
        context.lineTo(196.88, 288.45);
        context.bezierCurveTo(196.5, 289.81, 195.67, 290.6, 194.29, 290.98);
        context.lineTo(195.63, 294.52);
        context.lineTo(193.21, 294.52);
        context.lineTo(191.96, 291.25);
        context.lineTo(191.82, 291.25);
        context.lineTo(189.86, 291.24);
        context.lineTo(188.92, 294.52);
        context.lineTo(186.71, 294.52);
        context.lineTo(189.46, 284.91);
        context.lineTo(193.64, 284.91);
        context.bezierCurveTo(196.07, 284.89, 197.28, 285.43, 197.25, 286.79);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 56 Drawing
        context.beginPath();
        context.moveTo(200.87, 284.91);
        context.lineTo(203.08, 284.91);
        context.lineTo(200.33, 294.52);
        context.lineTo(198.12, 294.52);
        context.lineTo(200.87, 284.91);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 57 Drawing
        context.beginPath();
        context.moveTo(213.52, 286.46);
        context.lineTo(210.33, 286.46);
        context.lineTo(208.02, 294.52);
        context.lineTo(205.8, 294.52);
        context.lineTo(208.12, 286.46);
        context.lineTo(204.94, 286.46);
        context.lineTo(205.39, 284.91);
        context.lineTo(213.95, 284.91);
        context.lineTo(213.52, 286.46);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 58 Drawing
        context.beginPath();
        context.moveTo(216.26, 284.91);
        context.lineTo(218.47, 284.91);
        context.lineTo(215.72, 294.52);
        context.lineTo(213.51, 294.52);
        context.lineTo(216.26, 284.91);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 59 Drawing
        context.beginPath();
        context.moveTo(226, 291.07);
        context.lineTo(226.8, 288.33);
        context.bezierCurveTo(226.91, 287.87, 227, 287.5, 227.01, 287.2);
        context.bezierCurveTo(227.03, 286.45, 226.58, 286.13, 225.35, 286.13);
        context.bezierCurveTo(223.62, 286.13, 223.09, 286.75, 222.64, 288.33);
        context.lineTo(221.86, 291.07);
        context.bezierCurveTo(221.73, 291.53, 221.66, 291.9, 221.65, 292.21);
        context.bezierCurveTo(221.64, 292.95, 222.07, 293.27, 223.3, 293.27);
        context.bezierCurveTo(225.03, 293.27, 225.57, 292.65, 226, 291.07);
        context.closePath();
        context.moveTo(219.32, 292.64);
        context.bezierCurveTo(219.32, 292.31, 219.4, 291.94, 219.52, 291.51);
        context.lineTo(220.56, 287.9);
        context.bezierCurveTo(221.25, 285.51, 222.83, 284.77, 225.73, 284.77);
        context.bezierCurveTo(228.12, 284.77, 229.35, 285.28, 229.33, 286.78);
        context.bezierCurveTo(229.32, 287.09, 229.26, 287.48, 229.12, 287.9);
        context.lineTo(228.1, 291.51);
        context.bezierCurveTo(227.41, 293.89, 225.81, 294.64, 222.91, 294.64);
        context.bezierCurveTo(220.54, 294.64, 219.29, 294.14, 219.32, 292.64);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 60 Drawing
        context.beginPath();
        context.moveTo(241.44, 284.91);
        context.lineTo(238.69, 294.52);
        context.lineTo(236.62, 294.52);
        context.lineTo(233.83, 288.19);
        context.lineTo(232.02, 294.52);
        context.lineTo(230.11, 294.52);
        context.lineTo(232.86, 284.91);
        context.lineTo(234.84, 284.91);
        context.lineTo(237.63, 291.57);
        context.lineTo(239.53, 284.91);
        context.lineTo(241.44, 284.91);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 61 Drawing
        context.beginPath();
        context.moveTo(248.21, 291.48);
        context.lineTo(247.9, 286.71);
        context.lineTo(244.89, 291.48);
        context.lineTo(248.21, 291.48);
        context.closePath();
        context.moveTo(248.31, 293.04);
        context.lineTo(243.9, 293.04);
        context.lineTo(242.96, 294.52);
        context.lineTo(240.93, 294.52);
        context.lineTo(247.16, 284.91);
        context.lineTo(249.97, 284.91);
        context.lineTo(250.68, 294.52);
        context.lineTo(248.4, 294.52);
        context.lineTo(248.31, 293.04);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 62 Drawing
        context.beginPath();
        context.moveTo(259.87, 292.97);
        context.lineTo(259.42, 294.52);
        context.lineTo(252.94, 294.52);
        context.lineTo(255.68, 284.91);
        context.lineTo(257.89, 284.91);
        context.lineTo(255.59, 292.97);
        context.lineTo(259.87, 292.97);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 63 Drawing
        context.beginPath();
        context.moveTo(112.21, 310.17);
        context.bezierCurveTo(112.22, 309.98, 112.25, 309.79, 112.31, 309.57);
        context.lineTo(112.57, 308.67);
        context.lineTo(114.78, 308.67);
        context.lineTo(114.58, 309.36);
        context.bezierCurveTo(114.55, 309.49, 114.52, 309.6, 114.51, 309.7);
        context.bezierCurveTo(114.5, 310.39, 115.21, 310.73, 116.28, 310.73);
        context.bezierCurveTo(117.49, 310.73, 118.5, 310.28, 118.72, 309.4);
        context.lineTo(118.81, 309.11);
        context.bezierCurveTo(118.85, 308.92, 118.89, 308.76, 118.89, 308.62);
        context.bezierCurveTo(118.89, 308.18, 118.58, 307.96, 117.85, 307.93);
        context.lineTo(115.76, 307.86);
        context.bezierCurveTo(114.05, 307.82, 113.29, 307.37, 113.31, 306.33);
        context.bezierCurveTo(113.32, 306.08, 113.36, 305.83, 113.45, 305.53);
        context.lineTo(113.61, 304.96);
        context.bezierCurveTo(114.18, 302.84, 116.51, 302.22, 118.66, 302.22);
        context.bezierCurveTo(120.63, 302.22, 122.37, 302.72, 122.34, 304.17);
        context.bezierCurveTo(122.34, 304.36, 122.3, 304.57, 122.24, 304.79);
        context.lineTo(121.99, 305.66);
        context.lineTo(119.78, 305.66);
        context.lineTo(119.97, 305.01);
        context.bezierCurveTo(120, 304.87, 120.02, 304.75, 120.03, 304.64);
        context.bezierCurveTo(120.04, 303.92, 119.35, 303.6, 118.28, 303.6);
        context.bezierCurveTo(117.07, 303.6, 116.06, 304.04, 115.82, 304.96);
        context.lineTo(115.75, 305.24);
        context.bezierCurveTo(115.7, 305.41, 115.68, 305.56, 115.67, 305.68);
        context.bezierCurveTo(115.66, 306.19, 115.99, 306.43, 116.7, 306.44);
        context.lineTo(118.8, 306.51);
        context.bezierCurveTo(120.53, 306.56, 121.28, 307.01, 121.26, 307.95);
        context.bezierCurveTo(121.26, 308.17, 121.23, 308.4, 121.14, 308.67);
        context.lineTo(120.93, 309.42);
        context.bezierCurveTo(120.36, 311.48, 118.04, 312.09, 115.9, 312.09);
        context.bezierCurveTo(113.91, 312.09, 112.19, 311.6, 112.21, 310.17);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 64 Drawing
        context.beginPath();
        context.moveTo(123.65, 310.09);
        context.bezierCurveTo(123.65, 309.77, 123.73, 309.4, 123.84, 308.98);
        context.lineTo(125.71, 302.37);
        context.lineTo(127.92, 302.37);
        context.lineTo(126.17, 308.55);
        context.bezierCurveTo(126.04, 309, 125.96, 309.37, 125.96, 309.68);
        context.bezierCurveTo(125.95, 310.43, 126.38, 310.73, 127.61, 310.73);
        context.bezierCurveTo(129.34, 310.73, 129.88, 310.12, 130.33, 308.55);
        context.lineTo(132.09, 302.37);
        context.lineTo(134.3, 302.37);
        context.lineTo(132.43, 308.98);
        context.bezierCurveTo(131.75, 311.35, 130.13, 312.11, 127.23, 312.11);
        context.bezierCurveTo(124.86, 312.11, 123.62, 311.6, 123.65, 310.09);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 65 Drawing
        context.beginPath();
        context.moveTo(142.72, 304.72);
        context.bezierCurveTo(142.73, 304.06, 142.32, 303.73, 141.03, 303.73);
        context.lineTo(139.07, 303.73);
        context.lineTo(137.99, 307.52);
        context.lineTo(139.95, 307.53);
        context.bezierCurveTo(141.67, 307.55, 142.2, 306.95, 142.51, 305.79);
        context.lineTo(142.58, 305.49);
        context.bezierCurveTo(142.67, 305.19, 142.72, 304.94, 142.72, 304.72);
        context.closePath();
        context.moveTo(145.05, 304.26);
        context.bezierCurveTo(145.04, 304.52, 144.98, 304.82, 144.89, 305.15);
        context.lineTo(144.62, 306.12);
        context.bezierCurveTo(144.04, 308.18, 142.44, 308.93, 139.55, 308.92);
        context.lineTo(137.59, 308.91);
        context.lineTo(136.72, 311.98);
        context.lineTo(134.5, 311.98);
        context.lineTo(137.25, 302.37);
        context.lineTo(141.43, 302.37);
        context.bezierCurveTo(143.86, 302.36, 145.07, 302.9, 145.05, 304.26);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 66 Drawing
        context.beginPath();
        context.moveTo(153.71, 304.72);
        context.bezierCurveTo(153.72, 304.06, 153.31, 303.73, 152.02, 303.73);
        context.lineTo(150.06, 303.73);
        context.lineTo(148.98, 307.52);
        context.lineTo(150.94, 307.53);
        context.bezierCurveTo(152.66, 307.55, 153.19, 306.95, 153.5, 305.79);
        context.lineTo(153.57, 305.49);
        context.bezierCurveTo(153.66, 305.19, 153.7, 304.94, 153.71, 304.72);
        context.closePath();
        context.moveTo(156.04, 304.26);
        context.bezierCurveTo(156.03, 304.52, 155.97, 304.82, 155.88, 305.15);
        context.lineTo(155.61, 306.12);
        context.bezierCurveTo(155.03, 308.18, 153.42, 308.93, 150.54, 308.92);
        context.lineTo(148.58, 308.91);
        context.lineTo(147.7, 311.98);
        context.lineTo(145.49, 311.98);
        context.lineTo(148.24, 302.37);
        context.lineTo(152.41, 302.37);
        context.bezierCurveTo(154.84, 302.36, 156.06, 302.9, 156.04, 304.26);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 67 Drawing
        context.beginPath();
        context.moveTo(163.44, 310.43);
        context.lineTo(162.98, 311.98);
        context.lineTo(156.5, 311.98);
        context.lineTo(159.25, 302.37);
        context.lineTo(161.46, 302.37);
        context.lineTo(159.15, 310.43);
        context.lineTo(163.44, 310.43);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 68 Drawing
        context.beginPath();
        context.moveTo(169.89, 303.92);
        context.lineTo(169.21, 306.26);
        context.lineTo(173.69, 306.26);
        context.lineTo(173.25, 307.81);
        context.lineTo(168.78, 307.81);
        context.lineTo(168.02, 310.43);
        context.lineTo(172.51, 310.43);
        context.lineTo(172.05, 311.98);
        context.lineTo(165.37, 311.98);
        context.lineTo(168.11, 302.37);
        context.lineTo(174.8, 302.37);
        context.lineTo(174.36, 303.92);
        context.lineTo(169.89, 303.92);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 69 Drawing
        context.beginPath();
        context.moveTo(188.56, 302.37);
        context.lineTo(185.81, 311.98);
        context.lineTo(183.7, 311.98);
        context.lineTo(185.71, 304.96);
        context.lineTo(180.97, 311.98);
        context.lineTo(179.52, 311.98);
        context.lineTo(178.8, 305);
        context.lineTo(176.8, 311.98);
        context.lineTo(174.95, 311.98);
        context.lineTo(177.69, 302.37);
        context.lineTo(180.65, 302.37);
        context.lineTo(181.34, 308.9);
        context.lineTo(185.67, 302.37);
        context.lineTo(188.56, 302.37);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 70 Drawing
        context.beginPath();
        context.moveTo(193.34, 303.92);
        context.lineTo(192.67, 306.26);
        context.lineTo(197.15, 306.26);
        context.lineTo(196.71, 307.81);
        context.lineTo(192.24, 307.81);
        context.lineTo(191.47, 310.43);
        context.lineTo(195.97, 310.43);
        context.lineTo(195.51, 311.98);
        context.lineTo(188.83, 311.98);
        context.lineTo(191.57, 302.37);
        context.lineTo(198.26, 302.37);
        context.lineTo(197.82, 303.92);
        context.lineTo(193.34, 303.92);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 71 Drawing
        context.beginPath();
        context.moveTo(209.73, 302.37);
        context.lineTo(206.99, 311.98);
        context.lineTo(204.91, 311.98);
        context.lineTo(202.13, 305.66);
        context.lineTo(200.31, 311.98);
        context.lineTo(198.4, 311.98);
        context.lineTo(201.15, 302.37);
        context.lineTo(203.12, 302.37);
        context.lineTo(205.93, 309.03);
        context.lineTo(207.82, 302.37);
        context.lineTo(209.73, 302.37);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 72 Drawing
        context.beginPath();
        context.moveTo(220.16, 303.92);
        context.lineTo(216.97, 303.92);
        context.lineTo(214.67, 311.98);
        context.lineTo(212.45, 311.98);
        context.lineTo(214.76, 303.92);
        context.lineTo(211.58, 303.92);
        context.lineTo(212.03, 302.37);
        context.lineTo(220.6, 302.37);
        context.lineTo(220.16, 303.92);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Bezier 73 Drawing
        context.beginPath();
        context.moveTo(220.58, 310.17);
        context.bezierCurveTo(220.59, 309.98, 220.62, 309.79, 220.68, 309.57);
        context.lineTo(220.94, 308.67);
        context.lineTo(223.15, 308.67);
        context.lineTo(222.95, 309.36);
        context.bezierCurveTo(222.91, 309.49, 222.89, 309.6, 222.88, 309.7);
        context.bezierCurveTo(222.87, 310.39, 223.58, 310.73, 224.65, 310.73);
        context.bezierCurveTo(225.86, 310.73, 226.87, 310.28, 227.09, 309.4);
        context.lineTo(227.18, 309.11);
        context.bezierCurveTo(227.22, 308.92, 227.26, 308.76, 227.26, 308.62);
        context.bezierCurveTo(227.26, 308.18, 226.95, 307.96, 226.22, 307.93);
        context.lineTo(224.12, 307.86);
        context.bezierCurveTo(222.42, 307.82, 221.66, 307.37, 221.68, 306.33);
        context.bezierCurveTo(221.68, 306.08, 221.73, 305.83, 221.82, 305.53);
        context.lineTo(221.98, 304.96);
        context.bezierCurveTo(222.55, 302.84, 224.88, 302.22, 227.03, 302.22);
        context.bezierCurveTo(229, 302.22, 230.73, 302.72, 230.71, 304.17);
        context.bezierCurveTo(230.71, 304.36, 230.66, 304.57, 230.61, 304.79);
        context.lineTo(230.36, 305.66);
        context.lineTo(228.15, 305.66);
        context.lineTo(228.34, 305.01);
        context.bezierCurveTo(228.36, 304.87, 228.39, 304.75, 228.39, 304.64);
        context.bezierCurveTo(228.41, 303.92, 227.71, 303.6, 226.64, 303.6);
        context.bezierCurveTo(225.43, 303.6, 224.43, 304.04, 224.19, 304.96);
        context.lineTo(224.12, 305.24);
        context.bezierCurveTo(224.07, 305.41, 224.04, 305.56, 224.04, 305.68);
        context.bezierCurveTo(224.03, 306.19, 224.36, 306.43, 225.07, 306.44);
        context.lineTo(227.17, 306.51);
        context.bezierCurveTo(228.9, 306.56, 229.65, 307.01, 229.63, 307.95);
        context.bezierCurveTo(229.63, 308.17, 229.6, 308.4, 229.51, 308.67);
        context.lineTo(229.3, 309.42);
        context.bezierCurveTo(228.73, 311.48, 226.41, 312.09, 224.27, 312.09);
        context.bezierCurveTo(222.28, 312.09, 220.55, 311.6, 220.58, 310.17);
        context.closePath();
        context.fillStyle = fillColor5;
        context.fill();


        //// Oval 5 Drawing




        //// Text Drawing
        var textRect = makeRect(318, 200, 757, 185);
        context.fillStyle = 'rgb(0, 0, 0)';
        context.font = '67.5px HelveticaNeue, "Helvetica Neue", Helvetica, Arial, sans-serif';
        context.textAlign = 'left';
        var textTotalHeight = 67.5 * 1.3;
        context.fillText('Website Coming Soon…', textRect.x, textRect.y + 64 + textRect.h / 2 - textTotalHeight / 2);
        
        context.restore();

    }

    //// Infrastructure

    function clearCanvas(canvas) {
        canvas = initializeCanvas(typeof canvas === 'string' ? document.getElementById(canvas) : canvas);
        canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height);
    }

    // Possible arguments for 'resizing' parameter are:
    //   'aspectfit': The content is proportionally resized to fit into the target rectangle.
    //   'aspectfill': The content is proportionally resized to completely fill the target rectangle.
    //   'stretch': The content is stretched to match the entire target rectangle.
    //   'center': The content is centered in the target rectangle, but it is NOT resized.
    function applyResizingBehavior(resizing, rect, targetRect) {
        if (targetRect === undefined || equalRects(rect, targetRect) || equalRects(targetRect, makeRect(0, 0, 0, 0))) {
            return rect;
        }

        var scales = makeSize(0, 0);
        scales.w = Math.abs(targetRect.w / rect.w);
        scales.h = Math.abs(targetRect.h / rect.h);

        switch (resizing) {
            case 'aspectfit': {
                scales.w = Math.min(scales.w, scales.h);
                scales.h = scales.w;
                break;
            }
            case 'aspectfill': {
                scales.w = Math.max(scales.w, scales.h);
                scales.h = scales.w;
                break;
            }
            case 'stretch':
            case undefined:
                break;
            case 'center': {
                scales.w = 1;
                scales.h = 1;
                break;
            }
            default:
                throw 'Unknown resizing behavior "' + resizing + '". Use "aspectfit", "aspectfill", "stretch" or "center" as resizing behavior.';
        }

        var result = makeRect(Math.min(rect.x, rect.x + rect.w), Math.min(rect.y, rect.y + rect.h), Math.abs(rect.w), Math.abs(rect.h));
        result.w *= scales.w;
        result.h *= scales.h;
        result.x = targetRect.x + (targetRect.w - result.w) / 2;
        result.y = targetRect.y + (targetRect.h - result.h) / 2;
        return result;
    }

    function oval(context, x, y, w, h) {
        context.save();
        context.beginPath();
        context.translate(x, y);
        context.scale(w/2, h/2);
        context.arc(1, 1, 1, 0, 2*Math.PI, false);
        context.closePath();
        context.restore();
    }

    function makeRect(x, y, w, h) {
        return { x: x, y: y, w: w, h: h };
    }

    function equalRects(r1, r2) {
        return r1.x === r2.x && r1.y === r2.y && r1.w == r2.w && r1.h === r2.h;
    }

    function makeSize(w, h) {
        return { w: w, h: h };
    }

    function initializeCanvas(canvas) {
        if ('paintCodePixelRatio' in canvas) return canvas;
        // This function should only be called once on each canvas.
        var context = canvas.getContext('2d');

        var devicePixelRatio = window.devicePixelRatio || 1;
        var backingStorePixelRatio = context.webkitBackingStorePixelRatio
            || context.mozBackingStorePixelRatio
            || context.msBackingStorePixelRatio
            || context.oBackingStorePixelRatio
            || context.backingStorePixelRatio
            || 1;

        var pixelRatio = devicePixelRatio / backingStorePixelRatio;

        canvas.style.width = canvas.width + 'px';
        canvas.style.height = canvas.height + 'px';
        canvas.width *= pixelRatio;
        canvas.height *= pixelRatio;
        canvas.paintCodePixelRatio = pixelRatio;

        context.scale(pixelRatio, pixelRatio);
        return canvas;
    }

    //// Public Interface

    // Drawing Methods
    StyleKitName.drawLogosPage1Canvas = drawLogosPage1Canvas;

    // Utilities
    StyleKitName.clearCanvas = clearCanvas;
    StyleKitName.makeRect = makeRect;

})();
